import { defineConfig } from 'vitepress'

// https://notetester.github.io/TripTogetherLearning/
export default defineConfig({
  lang: 'ko-KR',
  title: 'TripTogether Learning',
  description: 'TripTogether(여행 올인원 플랫폼) 프로젝트를 면접에서 설명하기 위한 학습 자료 — 도메인별 심화 + 담당 태그 필터',
  base: '/TripTogetherLearning/',
  lastUpdated: true,
  cleanUrls: true,
  ignoreDeadLinks: true,

  head: [
    ['meta', { name: 'theme-color', content: '#0ea5a4' }],
  ],

  themeConfig: {
    outline: { level: [2, 3], label: '목차' },
    docFooter: { prev: '이전', next: '다음' },
    darkModeSwitchLabel: '테마',
    sidebarMenuLabel: '메뉴',
    returnToTopLabel: '맨 위로',
    lastUpdatedText: '마지막 수정',
    search: {
      provider: 'local',
      options: {
        translations: {
          button: { buttonText: '검색', buttonAriaLabel: '검색' },
          modal: { noResultsText: '결과 없음', resetButtonTitle: '지우기', footer: { selectText: '선택', navigateText: '이동', closeText: '닫기' } },
        },
      },
    },

    nav: [
      { text: '홈', link: '/' },
      { text: '학습법', link: '/guide/how-to-study' },
      { text: '용어집', link: '/glossary/' },
      { text: '백엔드', link: '/backend/' },
      {
        text: '도메인별 심화',
        items: [
          { text: '🗂️ 전체 개요', link: '/domains' },
          { text: '인증·계정·보안', link: '/auth/' },
          { text: '커뮤니티·신고', link: '/community/' },
          { text: '문의·알림·마이페이지', link: '/inquiry/' },
          { text: '여행 코스·AI 일정', link: '/courses/' },
          { text: '여행지 탐색·커머스', link: '/explore/' },
          { text: 'AI 어시스턴트·챗봇', link: '/assistant/' },
          { text: '관리자·운영', link: '/admin/' },
          { text: '다국어·공통', link: '/i18n/' },
        ],
      },
      { text: 'AI', link: '/ai/' },
      { text: '전체 흐름', link: '/flow/' },
      { text: '담당별 보기', link: '/by-area/' },
      { text: '인프라', link: '/infra/' },
      { text: '퀴즈', link: '/quizzes/' },
    ],

    sidebar: {
      '/guide/': [
        { text: '학습 가이드', items: [
          { text: '학습/말하기 전략', link: '/guide/how-to-study' },
          { text: '기술 지도 (전 도메인)', link: '/guide/tech-map' },
          { text: '담당별 보기 (태그 필터)', link: '/by-area/' },
        ]},
      ],
      '/glossary/': [
        { text: '기초 용어집', items: [
          { text: '개요', link: '/glossary/' },
          { text: 'API', link: '/glossary/api' },
          { text: 'REST', link: '/glossary/rest' },
          { text: 'HTTP 메서드·상태코드', link: '/glossary/http-methods' },
          { text: 'JSON', link: '/glossary/json' },
          { text: 'DTO / VO', link: '/glossary/dto-vo' },
          { text: '4계층 구조', link: '/glossary/layered-architecture' },
          { text: 'ORM과 MyBatis', link: '/glossary/mybatis-orm' },
          { text: '트랜잭션', link: '/glossary/transaction' },
          { text: '세션 / 쿠키', link: '/glossary/session-cookie' },
          { text: 'OAuth', link: '/glossary/oauth' },
          { text: 'BCrypt', link: '/glossary/bcrypt' },
          { text: '인터셉터', link: '/glossary/interceptor' },
          { text: 'AOP', link: '/glossary/aop' },
          { text: 'MVC와 JSP', link: '/glossary/mvc-jsp' },
          { text: '소프트 삭제', link: '/glossary/soft-delete' },
          { text: 'i18n (국제화)', link: '/glossary/i18n-term' },
          { text: 'SSE', link: '/glossary/sse' },
          { text: 'CSRF', link: '/glossary/csrf' },
        ]},
      ],
      '/backend/': [
        { text: '백엔드 (Spring Boot · MyBatis · JSP)', items: [
          { text: '개요', link: '/backend/' },
          { text: 'Spring Boot', link: '/backend/spring-boot' },
          { text: 'Spring MVC', link: '/backend/spring-mvc' },
          { text: 'MyBatis', link: '/backend/mybatis' },
          { text: 'MySQL 스키마', link: '/backend/mysql-schema' },
          { text: 'JSP · JSTL · EL', link: '/backend/jsp-jstl-el' },
          { text: '인터셉터 체인', link: '/backend/interceptors' },
          { text: 'AOP 권한 체크', link: '/backend/aop-authorization' },
          { text: '@LoginUser 리졸버', link: '/backend/login-user-resolver' },
          { text: '예외 처리', link: '/backend/exception-handling' },
          { text: '입력 검증', link: '/backend/validation' },
          { text: '파일 업로드 (Cloudinary)', link: '/backend/file-upload-cloudinary' },
          { text: '이메일 발송', link: '/backend/mail' },
          { text: '런타임 설정 (DB 우선)', link: '/backend/runtime-settings' },
          { text: 'HTTP 클라이언트 (OkHttp)', link: '/backend/okhttp' },
        ]},
      ],
      '/auth/': [
        { text: '인증·계정·보안', items: [
          { text: '개요', link: '/auth/' },
          { text: '로그인·세션', link: '/auth/login-session' },
          { text: 'OAuth 소셜 로그인', link: '/auth/oauth-social' },
          { text: '이메일 인증·액션 토큰', link: '/auth/email-verification-token' },
          { text: '비밀번호 해싱(BCrypt)', link: '/auth/password-bcrypt' },
          { text: '로그인 위험도 평가', link: '/auth/login-risk-assessment' },
          { text: '계정 복구·휴면', link: '/auth/account-recovery' },
          { text: '차단 해제 신청', link: '/auth/security-appeal' },
          { text: 'WAF 어댑터(AWS/Cloudflare)', link: '/auth/waf-adapters' },
          { text: '면접 플레이북', link: '/auth/interview-playbook' },
        ]},
      ],
      '/community/': [
        { text: '커뮤니티·신고', items: [
          { text: '개요', link: '/community/' },
          { text: '게시글 유형', link: '/community/post-types' },
          { text: '댓글·대댓글·채택', link: '/community/comments-replies' },
          { text: '좋아요·태그', link: '/community/likes-tags' },
          { text: '이미지(Cloudinary·Pixabay)', link: '/community/images' },
          { text: '독성 감지(Perspective)', link: '/community/toxicity-perspective' },
          { text: '3-스트라이크 블러', link: '/community/three-strike-blur' },
          { text: '네이티브 광고', link: '/community/native-ads' },
          { text: '신고 상태머신', link: '/community/report-system' },
          { text: '데이터 모델', link: '/community/data-model' },
          { text: '면접 플레이북', link: '/community/interview-playbook' },
        ]},
      ],
      '/inquiry/': [
        { text: '문의·알림·마이페이지', items: [
          { text: '개요', link: '/inquiry/' },
          { text: '문의 상태머신', link: '/inquiry/inquiry-statemachine' },
          { text: 'AI 답변 초안(Claude)', link: '/inquiry/ai-draft-claude' },
          { text: '첨부·비공개 워크플로우', link: '/inquiry/attachments-visibility' },
          { text: 'SSE 실시간 알림', link: '/inquiry/sse-notification' },
          { text: '알림 인터셉터·토스트', link: '/inquiry/notification-interceptor' },
          { text: '마이페이지 피드·크로스모듈', link: '/inquiry/mypage-feed' },
          { text: '면접 플레이북', link: '/inquiry/interview-playbook' },
        ]},
      ],
      '/courses/': [
        { text: '여행 코스·AI 일정', items: [
          { text: '개요', link: '/courses/' },
          { text: '직접 일정 작성', link: '/courses/manual-plan' },
          { text: '스팟 순서 관리', link: '/courses/plan-spot-ordering' },
          { text: 'AI 일정 생성(GPT)', link: '/courses/ai-plan-gpt' },
          { text: '구조화 출력(JSON Schema)', link: '/courses/structured-outputs' },
          { text: '공개 코스 피드', link: '/courses/public-feed' },
          { text: 'plan_source(MANUAL/AI)', link: '/courses/plan-source' },
          { text: 'CRUD·소유권', link: '/courses/crud-ownership' },
          { text: '면접 플레이북', link: '/courses/interview-playbook' },
        ]},
      ],
      '/explore/': [
        { text: '여행지 탐색·커머스·리워드', items: [
          { text: '개요', link: '/explore/' },
          { text: '탐색 필터', link: '/explore/explore-filters' },
          { text: 'AI 추천(Gemini)', link: '/explore/ai-recommendation-gemini' },
          { text: '추천 캐시·폴백', link: '/explore/recommendation-cache-fallback' },
          { text: '찜·좋아요·지도', link: '/explore/spot-favorite-maps' },
          { text: '항공권(Mock 프로바이더)', link: '/explore/flight-mock' },
          { text: 'Toss 결제', link: '/explore/toss-payments' },
          { text: '3원 지갑(캐시·마일리지·포인트)', link: '/explore/three-wallet' },
          { text: '게이미피케이션', link: '/explore/gamification' },
          { text: '패키지 마켓플레이스', link: '/explore/package-marketplace' },
          { text: '면접 플레이북', link: '/explore/interview-playbook' },
        ]},
      ],
      '/assistant/': [
        { text: 'AI 어시스턴트·챗봇', items: [
          { text: '개요', link: '/assistant/' },
          { text: '멀티턴 어시스턴트(GPT)', link: '/assistant/multiturn-gpt' },
          { text: '히스토리·DB 저장', link: '/assistant/history-management' },
          { text: '네비 챗봇(Gemini)', link: '/assistant/chatbot-gemini' },
          { text: '구조화 JSON 응답', link: '/assistant/structured-json' },
          { text: '의도 분류·Fast-Path', link: '/assistant/intent-fastpath' },
          { text: '등급별 쿼터', link: '/assistant/quota-grade' },
          { text: '차단·모더레이션', link: '/assistant/block-moderation' },
          { text: 'URL 화이트리스트 보안', link: '/assistant/url-whitelist' },
          { text: '면접 플레이북', link: '/assistant/interview-playbook' },
        ]},
      ],
      '/admin/': [
        { text: '관리자·운영', items: [
          { text: '개요', link: '/admin/' },
          { text: '관리자 대시보드', link: '/admin/dashboard' },
          { text: '회원 360 뷰', link: '/admin/member-360' },
          { text: '모더레이션 파이프라인', link: '/admin/moderation-pipeline' },
          { text: '감사 로그', link: '/admin/audit-logs' },
          { text: 'IP 차단(CIDR)', link: '/admin/ip-block-cidr' },
          { text: '런타임 설정', link: '/admin/runtime-settings' },
          { text: '권한 그룹', link: '/admin/permission-groups' },
          { text: 'superAdmin·조직', link: '/admin/superadmin-org' },
          { text: '매출·환불', link: '/admin/finance-refund' },
          { text: '데이터 내보내기(Excel)', link: '/admin/data-export' },
          { text: '면접 플레이북', link: '/admin/interview-playbook' },
        ]},
      ],
      '/i18n/': [
        { text: '다국어·공통 인프라', items: [
          { text: '개요', link: '/i18n/' },
          { text: 'MessageSource·properties', link: '/i18n/messagesource' },
          { text: 'LocaleResolver·언어전환', link: '/i18n/locale-resolver' },
          { text: 'Google 번역 API', link: '/i18n/google-translation' },
          { text: 'DB 번역 관리', link: '/i18n/db-translation' },
          { text: '면접 플레이북', link: '/i18n/interview-playbook' },
        ]},
      ],
      '/ai/': [
        { text: 'AI 전체', items: [
          { text: 'AI 기능 전체', link: '/ai/' },
          { text: '다중 AI 모델 통합', link: '/ai/multi-model' },
          { text: 'GPT 어시스턴트·일정', link: '/ai/gpt-assistant' },
          { text: 'Gemini 챗봇·추천', link: '/ai/gemini-chatbot' },
          { text: 'Claude 문의 초안', link: '/ai/claude-inquiry' },
          { text: 'Perspective 독성 감지', link: '/ai/perspective-toxicity' },
          { text: '구조화 출력', link: '/ai/structured-outputs' },
          { text: '폴백 전략', link: '/ai/fallback-strategy' },
        ]},
      ],
      '/flow/': [
        { text: '전체 흐름', items: [
          { text: '흐름 개요', link: '/flow/' },
          { text: '전체 아키텍처', link: '/flow/architecture' },
          { text: '사용자 여정(탐색→계획→예약→공유)', link: '/flow/user-journey' },
          { text: '인증·세션 흐름', link: '/flow/auth-session-flow' },
          { text: 'AI 통합 맵', link: '/flow/ai-integration-map' },
          { text: '알림 SSE 흐름', link: '/flow/notification-sse-flow' },
          { text: '모더레이션·거버넌스', link: '/flow/moderation-governance' },
          { text: '데이터 모델 전체', link: '/flow/data-model' },
          { text: '프로젝트 전체 면접 플레이북', link: '/flow/interview-whole-project' },
        ]},
      ],
      '/infra/': [
        { text: '인프라 / 협업', items: [
          { text: '개요', link: '/infra/' },
          { text: 'Maven · WAR 빌드', link: '/infra/maven-war' },
          { text: 'Tomcat 배포', link: '/infra/tomcat-deploy' },
          { text: 'Git 협업 전략', link: '/infra/git-workflow' },
          { text: 'ADR(MADR) 문서화', link: '/infra/adr-madr' },
          { text: 'JUnit 테스트', link: '/infra/junit-testing' },
          { text: '설정·시크릿 관리', link: '/infra/secrets-config' },
        ]},
      ],
      '/quizzes/': [
        { text: '퀴즈로 점검', items: [
          { text: '퀴즈 모음', link: '/quizzes/' },
          { text: '백엔드 퀴즈', link: '/quizzes/backend' },
          { text: '도메인 퀴즈', link: '/quizzes/domains' },
          { text: 'AI 퀴즈', link: '/quizzes/ai' },
          { text: '프로젝트 Q&A', link: '/quizzes/project-qna' },
        ]},
      ],
      '/by-area/': [
        { text: '담당별 보기', items: [
          { text: '태그 필터', link: '/by-area/' },
          { text: '도메인 전체 개요', link: '/domains' },
        ]},
      ],
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/notetester/TripTogetherLearning' },
    ],
    footer: {
      message: '팀 프로젝트 학습 자료 · 중립 서술 · 민감정보 미포함',
      copyright: 'TripTogether Learning',
    },
  },
})
